name: CD Pipeline - Sistem Pengingat Tugas

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t task-reminder-app .

      - name:  Deployment Successful
        run: |
          echo "======================================"
          echo " DEPLOYMENT BERHASIL!"
          echo "Sistem Otomatisasi Pengingat Tugas"
          echo "Telah berhasil di-deploy ke Production"
          echo "======================================"
